[package]
name = "unllm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/unllm"
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[features]
default = ["openai", "anthropic", "gemini"]
openai = ["dep:unllm-openai"]
anthropic = ["dep:unllm-anthropic"]
gemini = ["dep:unllm-gemini"]

[dependencies]
unllm-core = { path = "../unllm-core", version = "0.0.1" }
unllm-openai = { path = "../unllm-openai", version = "0.0.1", optional = true }
unllm-anthropic = { path = "../unllm-anthropic", version = "0.0.1", optional = true }
unllm-gemini = { path = "../unllm-gemini", version = "0.0.1", optional = true }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
